name: lestiterakhir
description: Sample Vania backend web application framework
version: 1.0.0

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  vania: ^0.6.2
  mysql1: 0.20.0  # Untuk koneksi MySQL
  shelf: ^1.3.0    # Untuk REST API
  shelf_router: ^1.1.0
  dart_json_mapper: ^2.2.7 # Untuk serialisasi model
  dotenv: ^4.2.0
  bcrypt: 1.1.3
  

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

dependency_overrides:
  pointycastle: 3.7.3